### ISSUE TITLE
too much space after Shrink.{u,v}

### ISSUE THREAD

**Issue by kbuzzard** [leanprover/doc-gen4#226]
I'm sorry, I don't know the first thing about doc-gen so this is a pretty lousy bug report, but right now at https://leanprover-community.github.io/mathlib4_docs/Mathlib/RingTheory/Flat/Basic.html#Module.Flat.of_shrink (which might not last for long because it's about to be removed :-/ ) there is too much space after `Small.{v', v}` and `Shrink.{v', v}`:

![shrink](https://github.com/user-attachments/assets/de396000-80c2-4f5e-a12f-ae30aea39178)

**Comment by Command-Master** [comment]
In general, there is a lot of space after types with two universe levels. This can also be noticed in most of category theory (e.g. https://leanprover-community.github.io/mathlib4_docs/Mathlib/CategoryTheory/Category/Basic.html)

**Comment by acmepjz** [comment]
Maybe you can see https://leanprover-community.github.io/mathlib4_docs/Mathlib/SetTheory/Cardinal/Basic.html#Cardinal.lift and results below it. Seems that there are a lot of extra spaces inserted (more spaces if `{...}` is longer), and the spaces are preserved.

**Comment by acmepjz** [comment]
Looks like that the following property in `style.css` is bogus:

```css
.fn {
    display: inline-block;
    /* border: 1px dashed red; */
    text-indent: -1ex;
    padding-left: 1ex;
    white-space: pre-wrap; /* this */
    vertical-align: top;
}
```

If I remove `white-space` property in developer mode of web browser, it solved.

So there are two possible solutions:

- Fix the code which inserts too many spaces.
- Fix the `css` file.
